/**
 * Evidence Matrix Builder
 * Creates evidence matrix linking requirements to evidence
 */

import * as fs from 'fs';
import * as path from 'path';
import { RequirementAssessment } from '../types';
import { MSP_REQUIREMENTS } from '../data/msp-requirements';

export interface EvidenceMatrixEntry {
  requirementId: string;
  requirementName: string;
  status: string;
  evidenceFiles: string[];
  gaps: string[];
}

/**
 * Build evidence matrix from assessments
 */
export function buildEvidenceMatrix(
  assessments: RequirementAssessment[],
  evidencePath: string
): EvidenceMatrixEntry[] {
  const matrix: EvidenceMatrixEntry[] = [];

  // Get list of evidence files
  const evidenceFiles = fs.existsSync(evidencePath)
    ? fs.readdirSync(evidencePath).filter((f) => f.endsWith('.json'))
    : [];

  for (const assessment of assessments) {
    // Find evidence files for this requirement
    const reqEvidence = evidenceFiles.filter((file) => {
      const content = fs.readFileSync(path.join(evidencePath, file), 'utf-8');
      return content.includes(assessment.requirement.id);
    });

    matrix.push({
      requirementId: assessment.requirement.id,
      requirementName: assessment.requirement.name,
      status: assessment.status,
      evidenceFiles: reqEvidence.length > 0 ? reqEvidence : ['TODO: Collect evidence'],
      gaps: assessment.gaps,
    });
  }

  return matrix;
}

/**
 * Generate evidence matrix markdown
 */
export function generateEvidenceMatrixMarkdown(
  matrix: EvidenceMatrixEntry[]
): string {
  const lines: string[] = [];

  lines.push('# Evidence Matrix\n');
  lines.push('**Generated**: ' + new Date().toISOString().split('T')[0] + '\n\n');
  lines.push('Links MSP requirements to collected evidence.\n\n');

  lines.push('## Summary\n\n');
  const addressed = matrix.filter((e) => e.status === 'addressed').length;
  const partial = matrix.filter((e) => e.status === 'partial').length;
  const gaps = matrix.filter((e) => e.status === 'gap').length;

  lines.push(`- ✅ **Addressed**: ${addressed} requirements\n`);
  lines.push(`- ⚠️ **Partial**: ${partial} requirements\n`);
  lines.push(`- ❌ **Gap**: ${gaps} requirements\n\n`);

  lines.push('## Evidence by Requirement\n\n');
  lines.push('| Requirement | Status | Evidence Files | Gaps |\n');
  lines.push('|-------------|--------|----------------|------|\n');

  for (const entry of matrix) {
    const icon =
      entry.status === 'addressed'
        ? '✅'
        : entry.status === 'partial'
          ? '⚠️'
          : '❌';

    const evidence = entry.evidenceFiles.join(', ');
    const gaps = entry.gaps.length > 0 ? entry.gaps.slice(0, 2).join('; ') : 'None';

    lines.push(
      `| ${icon} **${entry.requirementId}**: ${entry.requirementName} | ${entry.status} | ${evidence} | ${gaps} |\n`
    );
  }

  lines.push('\n## Action Items\n\n');
  const needEvidence = matrix.filter((e) =>
    e.evidenceFiles.some((f) => f.includes('TODO'))
  );

  if (needEvidence.length > 0) {
    lines.push('The following requirements need evidence collection:\n\n');
    for (const entry of needEvidence) {
      lines.push(`- **${entry.requirementId}**: ${entry.requirementName}\n`);
    }
  } else {
    lines.push('All requirements have evidence files collected.\n');
  }

  lines.push('\n---\n\n');
  lines.push('**🤖 Generated by MSP Readiness Automation**\n');

  return lines.join('');
}

/**
 * Save evidence matrix to file
 */
export function saveEvidenceMatrix(
  matrix: EvidenceMatrixEntry[],
  outputPath: string
): void {
  const markdown = generateEvidenceMatrixMarkdown(matrix);

  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, markdown, 'utf-8');
}

/**
 * Print evidence matrix summary
 */
export function printEvidenceMatrixSummary(matrix: EvidenceMatrixEntry[]): void {
  const addressed = matrix.filter((e) => e.status === 'addressed').length;
  const withEvidence = matrix.filter(
    (e) => !e.evidenceFiles.some((f) => f.includes('TODO'))
  ).length;

  console.log('Evidence Matrix:');
  console.log(`  Requirements: ${matrix.length}`);
  console.log(`  Addressed: ${addressed}`);
  console.log(`  With evidence: ${withEvidence}`);
  console.log('');
}
