/**
 * Generate Templates Command
 * Generate document templates for non-technical requirements
 */

import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { MSP_REQUIREMENTS } from '../data/msp-requirements';
import { RequirementCategory } from '../types';

interface GenerateTemplatesOptions {
  requirement?: string;
  category?: RequirementCategory;
  output: string;
  all?: boolean;
  force?: boolean;
}

interface TemplateInfo {
  requirementId: string;
  name: string;
  category: RequirementCategory;
  filename: string;
  content: string;
}

/**
 * Generate template content for a requirement
 */
function generateTemplateContent(requirementId: string, name: string, category: string): string {
  const timestamp = new Date().toISOString();

  return `---
requirement_id: ${requirementId}
title: ${name}
category: ${category}
status: draft
generated_at: ${timestamp}
---

# ${name}

**Requirement ID**: ${requirementId}
**Category**: ${category}
**Status**: Draft

## Overview

[Provide a brief overview of this ${name.toLowerCase()} and its purpose]

## Context

[Explain the business context and why this is important]

## Details

[Provide detailed information specific to this requirement]

### Key Components

1. **Component 1**: [Description]
2. **Component 2**: [Description]
3. **Component 3**: [Description]

## Implementation

[Describe how this is implemented in your organization]

### Current State

[Document the current state]

### Target State

[Document the desired target state]

## Evidence

The following artifacts support compliance with this requirement:

- [ ] Artifact 1
- [ ] Artifact 2
- [ ] Artifact 3

## References

- [AWS Documentation]()
- [Industry Best Practices]()

## Maintenance

**Review Schedule**: [Quarterly/Annual]
**Owner**: [Team/Role]
**Last Updated**: ${new Date().toISOString().split('T')[0]}

---
*Generated by MSP Readiness Automation*
`;
}

/**
 * Get template info for a requirement
 */
function getTemplateInfo(requirementId: string): TemplateInfo | null {
  const requirement = MSP_REQUIREMENTS.find(r => r.id === requirementId);

  if (!requirement) {
    return null;
  }

  // Only generate templates for non-technical requirements
  if (!['business', 'people', 'governance'].includes(requirement.category)) {
    return null;
  }

  const filename = `${requirementId.toLowerCase()}-${requirement.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')}.md`;

  const content = generateTemplateContent(requirementId, requirement.name, requirement.category);

  return {
    requirementId,
    name: requirement.name,
    category: requirement.category,
    filename,
    content,
  };
}

/**
 * Get all templates by category
 */
function getTemplatesByCategory(category: RequirementCategory): TemplateInfo[] {
  return MSP_REQUIREMENTS.filter(r => r.category === category)
    .map(r => getTemplateInfo(r.id))
    .filter((t): t is TemplateInfo => t !== null);
}

/**
 * Get all non-technical templates
 */
function getAllTemplates(): TemplateInfo[] {
  return MSP_REQUIREMENTS.filter(r => ['business', 'people', 'governance'].includes(r.category))
    .map(r => getTemplateInfo(r.id))
    .filter((t): t is TemplateInfo => t !== null);
}

/**
 * Save template to file
 */
function saveTemplate(
  template: TemplateInfo,
  outputDir: string,
  force: boolean = false
): { saved: boolean; path: string; reason?: string } {
  const categoryDir = path.join(outputDir, template.category);
  const filePath = path.join(categoryDir, template.filename);

  // Create category directory if needed
  if (!fs.existsSync(categoryDir)) {
    fs.mkdirSync(categoryDir, { recursive: true });
  }

  // Check if file exists
  if (fs.existsSync(filePath) && !force) {
    return {
      saved: false,
      path: filePath,
      reason: 'File exists (use --force to overwrite)',
    };
  }

  // Write file
  fs.writeFileSync(filePath, template.content, 'utf-8');

  return { saved: true, path: filePath };
}

/**
 * Execute generate-templates command
 */
export async function executeGenerateTemplates(options: GenerateTemplatesOptions): Promise<void> {
  console.log(chalk.bold.blue('\n📝 Generating Document Templates\n'));

  let templates: TemplateInfo[] = [];

  // Determine which templates to generate
  if (options.all) {
    templates = getAllTemplates();
    console.log(chalk.cyan(`Generating all ${templates.length} templates...\n`));
  } else if (options.requirement) {
    const template = getTemplateInfo(options.requirement);
    if (!template) {
      console.error(chalk.red(`❌ Invalid or non-template requirement: ${options.requirement}`));
      console.log(
        chalk.yellow('\nOnly business, people, and governance requirements support templates.')
      );
      process.exit(1);
    }
    templates = [template];
    console.log(chalk.cyan(`Generating template for ${options.requirement}...\n`));
  } else if (options.category) {
    templates = getTemplatesByCategory(options.category);
    if (templates.length === 0) {
      console.error(chalk.red(`❌ No templates available for category: ${options.category}`));
      console.log(chalk.yellow('\nValid categories: business, people, governance'));
      process.exit(1);
    }
    console.log(chalk.cyan(`Generating ${templates.length} ${options.category} templates...\n`));
  } else {
    console.error(chalk.red('❌ Must specify --all, --requirement, or --category'));
    process.exit(1);
  }

  // Generate templates
  const spinner = ora('Generating templates...').start();
  let savedCount = 0;
  let skippedCount = 0;
  const results: Array<{ template: TemplateInfo; result: ReturnType<typeof saveTemplate> }> = [];

  for (const template of templates) {
    const result = saveTemplate(template, options.output, options.force);
    results.push({ template, result });

    if (result.saved) {
      savedCount++;
    } else {
      skippedCount++;
    }
  }

  spinner.succeed(`Generated ${savedCount} template(s), skipped ${skippedCount}`);

  // Print results
  console.log();
  for (const { template, result } of results) {
    if (result.saved) {
      const relativePath = path.relative(process.cwd(), result.path);
      console.log(chalk.green(`✅ ${template.requirementId}: ${template.name}`));
      console.log(chalk.gray(`   → ${relativePath}`));
    } else {
      console.log(chalk.yellow(`⚠️  ${template.requirementId}: ${template.name}`));
      console.log(chalk.gray(`   ${result.reason}`));
    }
  }

  console.log(chalk.bold.green(`\n✅ Template generation complete!\n`));
  console.log(chalk.cyan(`Output directory: ${options.output}\n`));
}
